site_name: rivm
site_description: GraphQL API RIVM data
repo_url: https://github.com/eshatro/graphql-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/eshatro">eshatro</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
