# Generated by Django 3.1.7 on 2021-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
