# Generated by Django 3.1.7 on 2021-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivm', '0002_auto_20210722_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
