# Generated by Django 3.1.7 on 2021-07-22 21:52

from django.db import migrations


def forwards(apps, schema_editor):
    Geography = apps.get_model('rivm', 'Geography')
    Geography.objects.create(id="NL", short_name="NLD", name="The Netherlands")


class Migration(migrations.Migration):

    dependencies = [
        ('rivm', '0003_auto_20210722_2152'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
